on: [push, pull_request]
jobs:
  isotovideo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Zaoliang/isotovideo-action@main
        with:
          schedule: tests/console/save_ulog
      - uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: .
        if: always()
