name: Leaked Secrets Scan Test
on:
  pull_request:
  push:
    branches: [ "master" ]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@92f40c20316eca60e22caf82f425459e206b9fea
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
